# Day 23: Duplicate Data Removal

## Objective
Identify and remove duplicate records from a dataset using Pandas.

## Tools Used
- Python
- Pandas
- Jupyter Notebook

## Description
This task demonstrates how to identify duplicate rows, count duplicate records, remove duplicates, and compare the dataset before and after cleaning.

In [1]:
import pandas as pd

In [2]:
data = {
    "Name": [
        "Arun",
        "Priya",
        "Karthik",
        "Divya",
        "Arun",
        "Priya",
        "Rahul",
        "Karthik"
    ],
    "Age": [
        21, 22, 23, 21, 21, 22, 24, 23
    ],
    "Department": [
        "ECE",
        "CSE",
        "EEE",
        "ECE",
        "ECE",
        "CSE",
        "IT",
        "EEE"
    ]
}

df = pd.DataFrame(data)

df

      Name  Age Department
0     Arun   21        ECE
1    Priya   22        CSE
2  Karthik   23        EEE
3    Divya   21        ECE
4     Arun   21        ECE
5    Priya   22        CSE
6    Rahul   24         IT
7  Karthik   23        EEE

In [3]:
print("Original number of rows:", len(df))
print("Original number of columns:", len(df.columns))

Original number of rows: 8
Original number of columns: 3

In [4]:
duplicate_rows = df[df.duplicated()]

print("Number of duplicate records:", df.duplicated().sum())

duplicate_rows

Number of duplicate records: 3

      Name  Age Department
4     Arun   21        ECE
5    Priya   22        CSE
7  Karthik   23        EEE

In [5]:
df_cleaned = df.drop_duplicates()

df_cleaned

      Name  Age Department
0     Arun   21        ECE
1    Priya   22        CSE
2  Karthik   23        EEE
3    Divya   21        ECE
6    Rahul   24         IT

In [6]:
print("Before cleaning:", len(df), "rows")
print("After cleaning:", len(df_cleaned), "rows")
print("Rows removed:", len(df) - len(df_cleaned))
print("Remaining duplicate rows:", df_cleaned.duplicated().sum())

Before cleaning: 8 rows
After cleaning: 5 rows
Rows removed: 3
Remaining duplicate rows: 0

In [7]:
df_cleaned.to_csv("duplicate_data_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [8]:
cleaned_data = pd.read_csv("duplicate_data_cleaned.csv")

print("Saved dataset shape:", cleaned_data.shape)
print("Duplicate rows in saved dataset:", cleaned_data.duplicated().sum())

cleaned_data

Saved dataset shape: (5, 3)
Duplicate rows in saved dataset: 0

      Name  Age Department
0     Arun   21        ECE
1    Priya   22        CSE
2  Karthik   23        EEE
3    Divya   21        ECE
4    Rahul   24         IT

## Conclusion

Duplicate data removal was successfully performed using Pandas. The original dataset contained 8 rows, including 3 duplicate records. After applying `drop_duplicates()`, the cleaned dataset contained 5 unique rows. The cleaned dataset was exported to a CSV file for further analysis.